tests: arithmetics array dictionaries lists maths sets strings tuples

arithmetics: 
	python implementations/basics/arithmetics/test_arithmetics.py

array: 
	python implementations/basics/my_array/test_array.py

dictionaries:
	python implementations/basics/my_dictionaries/test_dictionaries.py

lists:
	python implementations/basics/my_lists/test_lists.py

maths:
	python implementations/basics/my_maths/test_maths.py

sets:
	python implementations/basics/my_sets/test_sets.py

strings:
	python implementations/basics/my_strings/test_strings.py

tuples:
	python implementations/basics/my_tuples/test_tuples.py